### ISSUE TITLE
Improve the look of the landing page

### ISSUE THREAD

**Issue by aritroCoder** [aritroCoder/ecohacks#1]
Here is the landing page now:
![image](https://user-images.githubusercontent.com/92646038/204895601-aa58bb93-a824-4b56-a7ca-b978ca8c1c5f.png)
Although the navbar and hero section looks good, the portion below it does not. 
<br/>
# Task required
Improve the UI of the content below the hero section

# Requirements
Keep in mind the color theme used in this website and try to design according to that

<br/>
Note: For really unique and creative design, it is possible that this issue fetches the points of a medium tagged issue

**Comment by shivamgupta2020** [comment]
I am interested. Please assign this to me.
Also  can u give me rough idea how u wanted to website look like?

**Comment by aritroCoder** [comment]
you can just adjust the alignments of the button to the center of the page, add the color theme I used in the upper sectons, and change the emoji to some custom vectors if you think it is looking good. Currently the landing page does not contain too much data, but it will show some more data in the future when backend is ready.

If you have seen the website you know that if you are logged out these contents are not shown instead you get a login button.
So for styling the page, you need to keep in mind that you will have to style both

If you are working on this issue just tell me to assign you first

**Comment by thevermaashutosh** [comment]
Bhaiya, I didn't get what you're trying to say about the look of the
website. Like when I go to www.moretrees.com it doesn't show any login
button.

And also which buttons are you telling me to align? The Home and the
Contact buttons?

Please clarify.

**Comment by tvermaashutosh** [comment]
Bhaiya, I'm ready to take this issue. Please assign it to me.

But, it's just that I'm not getting the actual website link. I landed onto www.moretrees.com which is a different website. Please give me the actual website link and please assign me this task.

**Comment by tvermaashutosh** [comment]
https://moretrees.eco/, https://www.more-trees.org/en/ these are some other websites with the same name but are different websites.
Which one's the one that we have to work upon?

**Comment by aritroCoder** [comment]
@shivamgupta2020 @thevermaashutosh I have assigned both of you whoever makes the PR first will get the points

**Comment by aritroCoder** [comment]
> Bhaiya, I'm ready to take this issue. Please assign it to me.
> 
> But, it's just that I'm not getting the actual website link. I landed onto [www.moretrees.com](http://www.moretrees.com) which is a different website. Please give me the actual website link and please assign me this task.

See you do not have to search it in the web. The code is here you need to run it in your PC. For instructions on how to run, please refer to the `readme.md` file in the code
Here is the readme file in case you are not finding it: https://github.com/aritroCoder/MoreTrees/blob/main/README.md

**Comment by shivamgupta2020** [comment]
> Here is the landing page now: ![image](https://user-images.githubusercontent.com/92646038/204895601-aa58bb93-a824-4b56-a7ca-b978ca8c1c5f.png) Although the navbar and hero section looks good, the portion below it does not.
> 
> # Task required
> Improve the UI of the content below the hero section
> 
> # Requirements
> Keep in mind the color theme used in this website and try to design according to that
> 
> 
> Note: For really unique and creative design, it is possible that this issue fetches the points of a medium tagged issue

I am not getting this as a landing page.
These options are not shown in the page
![image](https://user-images.githubusercontent.com/91847638/205673283-3945883d-90ad-4e99-ab42-0def95e2483e.png)

The signup and login feature is not working right now. I cannot access the webpage that needed to be fixed. 
I think there is some issue with mongoDB

**Comment by aritroCoder** [comment]
did you add your mongoDB URI in the env file?
If you are using local mongoDB server, it should look like: `mongodb://127.0.0.1:27017/?your_database_name`
If you are using mongoDB atlas, it should look like: `mongodb+srv://USER:XXPASSWORDXX@cluster0.nobsy.mongodb.net/your_database_name?retryWrites=true&w=majority`

**Comment by shivamgupta2020** [comment]
> did you add your mongoDB URI in the env file? If you are using local mongoDB server, it should look like: `mongodb://127.0.0.1:27017/?your_database_name` If you are using mongoDB atlas, it should look like: `mongodb+srv://USER:XXPASSWORDXX@cluster0.nobsy.mongodb.net/your_database_name?retryWrites=true&w=majority`

ohk
i haven't created mongoDB cluster. So can i contribute without making mongoDB cluster?(like only that page)

**Comment by aritroCoder** [comment]
> > did you add your mongoDB URI in the env file? If you are using local mongoDB server, it should look like: `mongodb://127.0.0.1:27017/?your_database_name` If you are using mongoDB atlas, it should look like: `mongodb+srv://USER:XXPASSWORDXX@cluster0.nobsy.mongodb.net/your_database_name?retryWrites=true&w=majority`
> 
> ohk i haven't created mongoDB cluster. So can i contribute without making mongoDB cluster?(like only that page)

Yes, you should be able to. Are you able to see the buttons that are present in my first comment (where I also uploaded a image)

**Comment by shivamgupta2020** [comment]
No

**Comment by shivamgupta2020** [comment]
if u already created cluster,
can u provide me?or I create my own cluster?

**Comment by aritroCoder** [comment]
> if u already created cluster, can u provide me?or I create my own cluster?

It is recommended that you create your own cluster because otherwise you wont be able to see what is going on in the database if you are working on a backend issue. But as you are working on a frontend issue, I suppose you could use some help while using mongoDB for the first time.

Just try with this link and tell me if it works: `mongodb+srv://testuser:cgfBXbObcJwcikDg@testcluster.llctihc.mongodb.net/moretrees`

**Comment by sankooru14** [comment]
@aritroCoder Can you assign this to me?

**Comment by aritroCoder** [comment]
@shivamgupta2020 @thevermaashutosh Are you working on it or should I assign it to him?

> @aritroCoder Can you assign this to me?

**Comment by shivamgupta2020** [comment]
> @shivamgupta2020 @thevermaashutosh Are you working on it or should I assign it to him?
> 
> > @aritroCoder Can you assign this to me?

I am working on this issue.

**Comment by aritroCoder** [comment]
> > @shivamgupta2020 @thevermaashutosh Are you working on it or should I assign it to him?
> > > @aritroCoder Can you assign this to me?
> 
> I am working on this issue.

Sure, keep on working then

**Comment by Tushar98644** [comment]
@aritroCoder if the issue is still not resolved ,can i work on this?

**Comment by aritroCoder** [comment]
> @aritroCoder if the issue is still not resolved ,can i work on this?

@shivamgupta2020 @tvermaashutosh any of you working on this or should I reassign?

**Comment by Tushar98644** [comment]
> > @aritroCoder if the issue is still not resolved ,can i work on this?
> 
> @shivamgupta2020 @tvermaashutosh any of you working on this or should I reassign?

I don't think anybody is working on it ....assign me @aritroCoder

**Comment by aritroCoder** [comment]
> > > @aritroCoder if the issue is still not resolved ,can i work on this?
> > 
> > 
> > @shivamgupta2020 @tvermaashutosh any of you working on this or should I reassign?
> 
> I don't think anybody is working on it ....assign me @aritroCoder

Sure, go ahead now
I am assigning you
