### ISSUE TITLE
A counter for total trees planted

### ISSUE THREAD

**Issue by Sparsh752** [aritroCoder/ecohacks#12]
There should be a live counter on any corner of the webpage which should show the total number of trees planted till now.

**Comment by aritroCoder** [comment]
You mean the total number of trees of the logged in user, or all the users combined?

**Comment by Sparsh752** [comment]
@aritroCoder all users combined

**Comment by aritroCoder** [comment]
Okay, looks reasonable. I am adding the relevant tags now

**Comment by nik132-eng** [comment]
can i take this issue?

**Comment by aritroCoder** [comment]
> can i take this issue?

Ya you can start working

**Comment by nik132-eng** [comment]
![image](https://user-images.githubusercontent.com/77881638/206698995-5187b1fa-d7cb-4d9d-a641-fb166994269b.png)

I tried, but I haven't worked with next JS much lately, so I can't really contribute much more.

**Comment by Sparsh752** [comment]
@aritroCoder Will I get points for raising the issue?

**Comment by aritroCoder** [comment]
> @aritroCoder Will I get points for raising the issue?

done, you got 3 points

**Comment by AaryaaRam** [comment]
@aritroCoder I would like to work on this!!

**Comment by aritroCoder** [comment]
okay, start working
