### ISSUE TITLE
Add a responsive Contact Us page  with real time map 

### ISSUE THREAD

**Issue by Tushar98644** [aritroCoder/ecohacks#14]

**Comment by Tushar98644** [comment]
pls assign me this .....

**Comment by aritroCoder** [comment]
Cool, I am assigning you

> pls assign me this .....

**Comment by Tushar98644** [comment]
@aritroCoder can u declare it a medium issue as i have also added the map feature ?

**Comment by aritroCoder** [comment]
> @aritroCoder can u declare it a medium issue as i have also added the map feature ?

You have used the google map's `iframe` tags right? Dude that's just a one liner 😂

**Comment by Tushar98644** [comment]
well...can't argue with that😅.....pls merge it if there seems to be no other problem....

**Comment by aritroCoder** [comment]
PR #15 closes the issue
