### ISSUE TITLE
Enhance UI of signup page

### ISSUE THREAD

**Issue by Tushar98644** [aritroCoder/ecohacks#18]
Right now the sign up page looks pretty inelegant, design and improve the UI of the page

**Comment by Tushar98644** [comment]
Assign me @aritroCoder

**Comment by aritroCoder** [comment]
Sure, you can start your work

**Comment by SattyamSamania** [comment]
@aritroCoder Can I work on this issue?

**Comment by aritroCoder** [comment]
> @aritroCoder Can I work on this issue?

A PR was under review for this issue, and it just got merged which means this issue is closed now. You can see the other open issues and try there
