### ISSUE TITLE
Add loader animation while loading pages or using API

### ISSUE THREAD

**Issue by aritroCoder** [aritroCoder/ecohacks#2]
Create or use an existing design of a loader that can be used throughout the website wherever loading is required, like API calls or page loading. Add the loader to all such existing places on the website currently.
<br/>
Note: Keep in mind the theme and color scheme while selecting any design that works.

**Comment by adrianmarinwork** [comment]
Hey, I can take care of this if you want!

**Comment by aritroCoder** [comment]
Contribution will start after codepeak 2022 begins

**Comment by jatin00000** [comment]
Hey! Can I work on this. I know how to implement it in effectively by creating a separate component for it.

**Comment by aritroCoder** [comment]
> Hey! Can I work on this. I know how to implement it in effectively by creating a separate component for it.

Sure, go ahead

**Comment by jatin00000** [comment]
Sorry, I tried but could not figure out the way.

**Comment by aritroCoder** [comment]
> Sorry, I tried but could not figure out the way.

If you have any queries in react/next or in the app you can ask

**Comment by AbhiPatel10** [comment]
I would love to work on this, assign this task to me

**Comment by aritroCoder** [comment]
> I would love to work on this, assign this task to me

Sure, go ahead!
