### ISSUE TITLE
Make the navbar responsive

### ISSUE THREAD

**Issue by aritroCoder** [aritroCoder/ecohacks#22]
Check the responsive ness of the navbar, it is not responsive. Instead of giving a fixed width it, try to use CSS flexbox to fix the issue. Weirdly, it behaves differently in the `/signup` page (maybe because width is hardcoded there). Try to fix this

Note: This will be a hard issue if contributor can add a hamburger menu and fetch 20 points.

**Comment by Tushar98644** [comment]
assign me @aritroCoder .....will also add a hamburger menu ....
