### ISSUE TITLE
Fix the login page

### ISSUE THREAD

**Issue by aritroCoder** [aritroCoder/ecohacks#23]
![image](https://user-images.githubusercontent.com/92646038/209899998-715d2641-58dd-42d3-9346-7d2278a049c8.png)

The login page is totally broken. I had implemented a simple login page before but it somehow got messed due to other contributor actiivity. It's time to fix it.

**task:** The input fields should be clear and visible

**Comment by Tushar98644** [comment]
assign me @aritroCoder

**Comment by Tushar98644** [comment]
completed previous issue ....now pls assign me this @aritroCoder

**Comment by Tushar98644** [comment]
would like to work on it now @aritroCoder

**Comment by aritroCoder** [comment]
start working
