### ISSUE TITLE
Fixes for Login modal in landing page

### ISSUE THREAD

**Issue by aritroCoder** [aritroCoder/ecohacks#24]
![image](https://user-images.githubusercontent.com/92646038/209900241-6491e2f6-5389-4b7d-a08e-9afab1b2e9ec.png)

**Tasks:**
1. add a button in the modal, so that if user clicks on it, he can go to the `/login` page
2. Add some spacing between elements, the modal looks really unrefined and incomplete
3. `Trees planted` and `remarks` section should only be shown when user is logged in
4. The modal looks too small when viewed in phone. The below image illustrates this. Make it larger

![image](https://user-images.githubusercontent.com/92646038/209946064-36a338e0-6242-4c2f-9a93-e81530fed5de.png)

**Comment by Tushar98644** [comment]
would like to implement it @aritroCoder

**Comment by nsundriyal62** [comment]
if no one working on this issue
can you please assign it to me?
