### ISSUE TITLE
Create a responsive footer for the website with all social media icons 

### ISSUE THREAD

**Issue by Tushar98644** [aritroCoder/ecohacks#27]

**Comment by SattyamSamania** [comment]
Hey @aritroCoder please assign this issue to me

**Comment by aritroCoder** [comment]
> Hey @aritroCoder please assign this issue to me

sure

**Comment by SattyamSamania** [comment]
> > Hey @aritroCoder please assign this issue to me
> 
> sure

Hey @aritroCoder Can I use react and make another file for that?

**Comment by aritroCoder** [comment]
> > > Hey @aritroCoder please assign this issue to me
> > 
> > 
> > sure
> 
> Hey @aritroCoder Can I use react and make another file for that?

yes you have to make that
