### ISSUE TITLE
Design UI for a blog page where users can bring issues related to nature in light 

### ISSUE THREAD

**Issue by Tushar98644** [aritroCoder/ecohacks#28]
#Reference :

<img width="1440" alt="Screenshot 2022-12-29 at 10 37 42 AM" src="https://user-images.githubusercontent.com/107763774/209906061-8c88ebf2-53e3-4e0e-801a-8234d384a194.png">

**Comment by Tushar98644** [comment]
Assign me this @aritroCoder

**Comment by aritroCoder** [comment]
> Assign me this @aritroCoder

start working
