### ISSUE TITLE
Design a responsive 'about us' page

### ISSUE THREAD

**Issue by aritroCoder** [aritroCoder/ecohacks#4]
A nice and simplistic design for the about us page will be appreciated.
Note: For this PR you might use any random text to fill in the about us page

**Comment by Babieshark** [comment]
I want to try this. Please assign it to me. Also, please explain what content/features etc. You want in the page.

**Comment by aritroCoder** [comment]
> I want to try this. Please assign it to me. Also, please explain what content/features etc. You want in the page.

See, here I don't really focus on content as I said in the first comment. All I want is a nice about us page. For ideas, you can visit different about us pages in other websites. Broadly speaking, it may contain a description section, where we describe what the website is about, a team section maybe where the team members working on the project can be listed, a contact section where contact details are present. You can use your creativity to add/remove sections

**Comment by SattyamSamania** [comment]
Hey @aritroCoder Can I also work on this issue?

**Comment by aritroCoder** [comment]
> Hey @aritroCoder Can I also work on this issue?

Sorry I have already assigned this issue to another contributor. There are some more unassigned issue left, you can try them

**Comment by sankooru14** [comment]
@aritroCoder  can you assign this to me?

**Comment by aritroCoder** [comment]
> @aritroCoder can you assign this to me?

Sorry this issue is assigned and the assignee is actively working

**Comment by Tushar98644** [comment]
assign me @aritroCoder if the issue is still open

**Comment by aritroCoder** [comment]
> assign me @aritroCoder if the issue is still open

The assignee is working in this issue

**Comment by Tushar98644** [comment]
It's been 3 weeks...i don't think anyone is working on it ....kindly assign @aritroCoder

**Comment by aritroCoder** [comment]
> It's been 3 weeks...i don't think anyone is working on it ....kindly assign @aritroCoder

Okay take up the issue
