### ISSUE TITLE
Design a user profile page

### ISSUE THREAD

**Issue by aritroCoder** [aritroCoder/ecohacks#5]
# Tasks:
1. Design a user profile page
2. Add the profile icon in the navbar, clicking which redirects to the user profile page

# Requirements:
1. Must display the user data received during sign up
2. It should also have a section where it shows the total number of trees planted by the user and a grouping of which specific trees are planted by the user (like how many apples, banana, cacti, and eucalyptus is planted)
3. All the different sections created must have their own components so that they can be reused if required.
4. For this issue you can use any random data to fill up the profile page components, but keep in mind that they will be used with an API so try to create your own JSON file like an API response and use its data to populate the page, so it will become easy to integrate an API later.

**Comment by tvermaashutosh** [comment]
I request you sir to assign me this issue. I am a participant of CodePeak'22.

**Comment by aritroCoder** [comment]
> I request you sir to assign me this issue. I am a participant of CodePeak'22.

Sure, go ahead

**Comment by tvermaashutosh** [comment]
Bhaiya where to create the `.env.local` file? It is written in the `readme.md` file that we have to create it in the root directory, but there are more than 1 root directories. So where to create `.env.local` file after installing the node modules?
![Screenshot (628)](https://user-images.githubusercontent.com/96707067/205592709-f7f263ce-911d-42ff-89ea-925a60378eb7.png)

**Comment by aritroCoder** [comment]
> Bhaiya where to create the `.env.local` file? It is written in the `readme.md` file that we have to create it in the root directory, but there are more than 1 root directories. So where to create `.env.local` file after installing the node modules? ![Screenshot (628)](https://user-images.githubusercontent.com/96707067/205592709-f7f263ce-911d-42ff-89ea-925a60378eb7.png)

See, here the `root` directory means the parent directory (the directory where the `node_modules` folder is present.  Here in the screenshot you can see which location I am talking about
![image](https://user-images.githubusercontent.com/92646038/205619072-4217dd81-7146-41a6-aa86-d9c6f89dc0f1.png)

This directory which contains all the project files is commonly called the `root` directory in programming literatures

**Comment by sankooru14** [comment]
@aritroCoder Can you assign this to me?

**Comment by aritroCoder** [comment]
> @aritroCoder Can you assign this to me?

@thevermaashutosh are you working on it or should I assign him?

**Comment by aritroCoder** [comment]
> @aritroCoder Can you assign this to me?

If you still want to work here message and I will assign you
