### ISSUE TITLE
Add an API endpoint to expose user profile information

### ISSUE THREAD

**Issue by aritroCoder** [aritroCoder/ecohacks#6]
Create an API that provides the user profile info given to it during sign-up as a JSON object. 
Note: This endpoint should only be accessible when logged in, and must require a valid auth token.

**Comment by ghost** [comment]
@aritroCoder  assign this to me

**Comment by aritroCoder** [comment]
> @aritroCoder assign this to me

Sure, go ahead

**Comment by RonitBaranwal** [comment]
If no one is working on this issue .Please assign it to me .

**Comment by tvermaashutosh** [comment]
string s;
vector<vector<int>> dp;
int recu(int i, int j, bool& isPal) {
if(i == j) {
isPal = true;
return 1;
} else if(i > j) {
isPal = true;
return 0;
} else if(dp[i][j] != -1) {
isPal = s[i] == s[j];
return dp[i][j];
}

int tmpLen;
if(s[i] == s[j]) {
tmpLen = recu(i + 1, j - 1, isPal);
if(isPal) {
isPal = true;
return dp[i][j] = tmpLen + 2;
} else {
tmpLen = max(recu(i + 1, j, isPal), recu(i, j - 1, isPal));
isPal = false;
return dp[i][j] = tmpLen;
}
} else {
tmpLen = max(recu(i + 1, j, isPal), recu(i, j - 1, isPal));
isPal = false;
return dp[i][j] = tmpLen;
}
}

[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
25/12/23,
14:37:05

**Comment by tvermaashutosh** [comment]
string recu(int i, int j, bool& isPal) {
if(i == j) {
isPal = true;
return string(1, s[i]);
} else if(i > j) {
isPal = true;
return "";
} else if(dp.count({i, j})) {
isPal = dp[{i, j}].size() == j - i + 1;
return dp[{i, j}];
}

string tmpStr;
if(s[i] == s[j]) {
tmpStr = recu(i + 1, j - 1, isPal);
if(isPal) {
isPal = true;
return dp[{i, j}] = s[i] + tmpStr + s[j];
} else {
string tmpStr_1 = recu(i + 1, j, isPal),
tmpStr_2 = recu(i, j - 1, isPal);
tmpStr = tmpStr_1.size() > tmpStr_2.size() ? tmpStr_1 : tmpStr_2;
isPal = false;
return dp[{i, j}] = tmpStr;
}
} else {
string tmpStr_1 = recu(i + 1, j, isPal),
tmpStr_2 = recu(i, j - 1, isPal);
tmpStr = tmpStr_1.size() > tmpStr_2.size() ? tmpStr_1 : tmpStr_2;
isPal = false;
return dp[{i, j}] = tmpStr;
}
}

**Comment by tvermaashutosh** [comment]
string longestPalindrome(string& s) {
string an;
for(int i = 0, n = s.size(); i < n; i++) {

string tmp(1, s[i]);
int l = i - 1, r = i + 1;
while(l >= 0 && r < n) {
if(s[l] == s[r]) tmp = s[l] + tmp + s[r];
else break;
l--, r++;
}
if(tmp.size() > an.size())
an = tmp;

tmp = "";
l = i, r = i + 1;
while(l >= 0 && r < n) {
if(s[l] == s[r]) tmp = s[l] + tmp + s[r];
else break;
l--, r++;
}
if(tmp.size() > an.size())
an = tmp;
}
return an;
}

[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
25/12/23,
15:52:00

**Comment by aritroCoder** [comment]
I'm sorry, we are not accepting any PRs on this project
