### ISSUE TITLE
Improve the 'plant a tree' feature

### ISSUE THREAD

**Issue by aritroCoder** [aritroCoder/ecohacks#7]
# Tasks:
1. In the select a tree page, add some more trees (modify in both frontend and backend)
2. Add different plant icons beside the name to make it more interactive
3. Create different taglines and designs on the landing page for different numbers of trees planted (like for 0, 1-5, 6-10, 10+ we can have different designs and punchlines on the landing page to encourage people!).

**Comment by Sparsh752** [comment]
@aritroCoder I would like to work on this issue

**Comment by aritroCoder** [comment]
> @aritroCoder I would like to work on this issue

Sure, go ahead

**Comment by Sparsh752** [comment]
@aritroCoder Can you tell me how many trees I must add and which trees should I add

**Comment by aritroCoder** [comment]
> @aritroCoder Can you tell me how many trees I must add and which trees should I add

I think there are 4 trees already, so add any 3-4 more trees (name doesnt matter as I can change them if needed)

**Comment by Sparsh752** [comment]
@aritroCoder ok

**Comment by Sparsh752** [comment]
@aritroCoder

**Comment by Sparsh752** [comment]
https://user-images.githubusercontent.com/94468600/206237345-27b7c136-1b4d-4ce0-9e1f-b1b70022bc18.mov

@aritroCoder I have added some more trees and icons as well. Also, I have added taglines. May I PR?

**Comment by aritroCoder** [comment]
> Screen.Recording.2022-12-07.at.21.59.52.mov 
> @aritroCoder I have added some more trees and icons as well. Also, I have added taglines. May I PR?

looks good to me!
You can make a PR now

**Comment by Sparsh752** [comment]
@aritroCoder I have PR, Kindly merge it
