### ISSUE TITLE
create a better readme 

### ISSUE THREAD

**Issue by aritroCoder** [aritroCoder/ecohacks#9]
This repo already has a readme, but it needs a better, more professional looking readme that explains what the website is about, how to set up and run the project, and contributing guidelines. This is open to contributer's creativity and sugessions about how they want to implement this. 

## Note
This is a non code contribution, the only knowledge you need to complete this is how markdown works, so non programmers or beginners can/should attempt this

**Comment by pranavajith** [comment]
Hey @aritroCoder 
This is my first time doing open source... could I get this as my first issue?

**Comment by aritroCoder** [comment]
> Hey @aritroCoder This is my first time doing open source... could I get this as my first issue?

Sure, go ahead

**Comment by SattyamSamania** [comment]
Hey @aritroCoder Can I work on this?

**Comment by aritroCoder** [comment]
> Hey @aritroCoder Can I work on this?

@pranavajith is already assigned this issue. He should respond with a solution or some progress within two days of being assigned, otherwise I can reassign this issue to you

**Comment by pranavajith** [comment]
Hey @aritroCoder 
Working on the readme at the moment... could you brief me a bit on what exactly needs to be in there? Just to make sure I dont miss out on anything

**Comment by pranavajith** [comment]
Such as.. would you want me to make a contributing.md file, or just combine the two in readme.md?

**Comment by aritroCoder** [comment]
> Such as.. would you want me to make a contributing.md file, or just combine the two in readme.md?

You can make a different `contributing.md` file also, It should contain in detail how to set and use the application, contributing guidelines (you can refer to any good readme on other repos for this), some links to docs for learning (for beginners) and maybe add some cool badges for different technologies used in the `readme`

**Comment by HetviSoni** [comment]
Hey @aritroCoder if @pranavajith is working on making README.md then I would like to work on making Contributing.md file where I would be writing all the steps for beginners to set up the project, create an issue to creating a pull request, and also add the figma design files if any. Please assign this issue if available.

**Comment by aritroCoder** [comment]
> Hey @aritroCoder if @pranavajith is working on making README.md then I would like to work on making Contributing.md file where I would be writing all the steps for beginners to set up the project, create an issue to creating a pull request, and also add the figma design files if any. Please assign this issue if available.

Okay you can work, I am assigning this issue to both of you but you will make the contributing.md
I havent decided much to put there, so if you can come up with some of your ideas it wouldbe great

**Comment by HetviSoni** [comment]
Hey @aritroCoder I can also work on making a professional-looking README file if this issue has not been done yet.

**Comment by aritroCoder** [comment]
> Hey @aritroCoder I can also work on making a professional-looking README file if this issue has not been done yet.

@pranavajith If you are working on this repo, please reply here within this day otherwise I'll assign her

**Comment by aritroCoder** [comment]
> Hey @aritroCoder I can also work on making a professional-looking README file if this issue has not been done yet.

Fine, you can start making the readme

**Comment by SattyamSamania** [comment]
@aritroCoder Can I work on this issue?

**Comment by aritroCoder** [comment]
@HetviSoni You working on it or should I reassign?

**Comment by HetviSoni** [comment]
Yes please reassign

**Comment by aritroCoder** [comment]
> @aritroCoder Can I work on this issue?

Ok you can start working

**Comment by SattyamSamania** [comment]
> > @aritroCoder Can I work on this issue?
> 
> Ok you can start working

Hey @aritroCoder What other features should I add in the Readme?

**Comment by aritroCoder** [comment]
> > > @aritroCoder Can I work on this issue?
> > 
> > 
> > Ok you can start working
> 
> Hey @aritroCoder What other features should I add in the Readme?

Add the texts in a formatted way, look at readme pages of other good repositories
like [this](https://github.com/ai/size-limit#readme)
also add some more sections about uses, internal working explanations (you have to read the codebase for this one).
you can refer other repos too
